AGID_DARWIN_DIR := $(AGID_DIR)/host-darwin 

AGID_HOST_SOURCE := \
    $(AGID_DIR)/host-darwin/macClasses.m \
    $(AGID_DIR)/host-darwin/os_main_mac.m   
    
AGID_INCLUDES += \
	-framework GLUT \
	-framework OpenGL \
	-framework AppKit \
	-framework CoreData \
	-framework Foundation \
	-framework Cocoa \
	-DDARWIN