MY_TARGET_IN := $(MY_TARGET)
MY_TARGETDIR_IN := $(MY_TARGETDIR)
MY_SRCDIR_IN := $(MY_SRCDIR)
MY_SRCS_IN := $(MY_SRCS)
MY_EXTRAOBJS_IN := $(MY_EXTRAOBJS)
MY_CFLAGS_IN := $(MY_CFLAGS)
MY_CPPFLAGS_IN := $(MY_CPPFLAGS)
MY_LDFLAGS_IN := $(MY_LDFLAGS)
MY_INCLUDES_IN := $(MY_INCLUDES)
MY_LIBS_IN := $(MY_LIBS)
MY_LIBPATHS_IN := $(MY_LIBPATHS)
MY_DEPS_IN := $(MY_DEPS)

$(warning MY_OBJS = $(MY_OBJS))

# extract the different source types out of the list
$(warning MY_SRCS_IN = $(MY_SRCS_IN))

#$(MY_TARGET_IN): MY_LDFLAGS_IN:=$(MY_LDFLAGS_IN)
#$(MY_TARGET_IN): MY_LIBS_IN:=$(MY_LIBS_IN)
#$(MY_TARGET_IN): MY_LIBPATHS_IN:=$(MY_LIBPATHS_IN)
#$(MY_TARGET_IN): _TEMP_OBJS:=$(_TEMP_OBJS)
$(MY_TARGET_IN):: $(_TEMP_OBJS) $(MY_DEPS_IN)
	@mkdir -p $(MY_TARGETDIR_IN)
	@echo pulling needed go deps
	@go get $(MY_GO_DEPS)
	@echo building cmd: $@
	@echo $(MY_GO_SRCS)
	@go build cmd/chaind/$(MY_GO_SRCS)
#	@$(CC) -L $(LIBGCC_PATH) -L $(LIBS_BUILD_DIR) $(MY_LIBPATHS_IN) -o $@ $(_TEMP_OBJS) $(MY_LIBS_IN) $(LIBGCC) 

MY_TARGET :=
MY_TARGETDIR :=
MY_SRCDIR :=
MY_SRCS :=
MY_EXTRAOBJS :=
MY_CFLAGS :=
MY_CPPFLAGS :=
MY_LDFLAGS :=
MY_INCLUDES :=
MY_LIBS :=
MY_LIBPATHS :=
MY_DEPS :=
MY_LINKSCRIPT := 
MY_GLUE :=
